#Music Player Configuration
#Mon Apr 06 18:20:38 MSK 2026
auto.create.dirs=true
cache.dir=C\:\\Users\\\u041E\u043B\u0435\u0433\\MusicPlayer\\cache
download.dir=C\:\\Users\\\u041E\u043B\u0435\u0433\\MusicPlayer\\downloads
max.concurrent.downloads=3
server.url=http\://127.0.0.1\:5098/
temp.dir=C\:\\Users\\08A4~1\\AppData\\Local\\Temp\\MusicPlayer
