// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicServer.API.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicServer.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251213205109_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicServer.API.Models.ExtraFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<int>("MusicFileId")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MusicFileId");

                    b.ToTable("ExtraFiles");
                });

            modelBuilder.Entity("MusicServer.API.Models.MusicFile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("album")
                        .HasColumnType("text");

                    b.Property<string>("artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("duration")
                        .HasColumnType("interval");

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("filepath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("filesize")
                        .HasColumnType("bigint");

                    b.Property<string>("genre")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("uploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("year")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("MusicFiles");
                });

            modelBuilder.Entity("MusicServer.API.Models.ExtraFile", b =>
                {
                    b.HasOne("MusicServer.API.Models.MusicFile", "MusicFile")
                        .WithMany("ExtraFiles")
                        .HasForeignKey("MusicFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicFile");
                });

            modelBuilder.Entity("MusicServer.API.Models.MusicFile", b =>
                {
                    b.Navigation("ExtraFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
