// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicServer.API.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicServer.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicServer.API.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Artists_Name");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("MusicServer.API.Models.ExtraFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FileExtensionId")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<int>("MusicFileId")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileExtensionId");

                    b.HasIndex("MusicFileId");

                    b.ToTable("ExtraFiles");
                });

            modelBuilder.Entity("MusicServer.API.Models.FileExtension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("FileExtensions");
                });

            modelBuilder.Entity("MusicServer.API.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Genres_Name");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MusicServer.API.Models.MusicFile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int?>("FileExtensionId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("album")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("duration")
                        .HasColumnType("interval");

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("filepath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("filesize")
                        .HasColumnType("bigint");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("uploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("year")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("FileExtensionId");

                    b.HasIndex("GenreId");

                    b.HasIndex("title")
                        .HasDatabaseName("IX_MusicFiles_Title");

                    b.ToTable("MusicFiles");
                });

            modelBuilder.Entity("MusicServer.API.Models.ExtraFile", b =>
                {
                    b.HasOne("MusicServer.API.Models.FileExtension", "FileExtension")
                        .WithMany("ExtraFiles")
                        .HasForeignKey("FileExtensionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MusicServer.API.Models.MusicFile", "MusicFile")
                        .WithMany("ExtraFiles")
                        .HasForeignKey("MusicFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileExtension");

                    b.Navigation("MusicFile");
                });

            modelBuilder.Entity("MusicServer.API.Models.MusicFile", b =>
                {
                    b.HasOne("MusicServer.API.Models.Artist", "artist")
                        .WithMany("MusicFiles")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("MusicServer.API.Models.FileExtension", "FileExtension")
                        .WithMany("MusicFiles")
                        .HasForeignKey("FileExtensionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MusicServer.API.Models.Genre", "genre")
                        .WithMany("MusicFiles")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("FileExtension");

                    b.Navigation("artist");

                    b.Navigation("genre");
                });

            modelBuilder.Entity("MusicServer.API.Models.Artist", b =>
                {
                    b.Navigation("MusicFiles");
                });

            modelBuilder.Entity("MusicServer.API.Models.FileExtension", b =>
                {
                    b.Navigation("ExtraFiles");

                    b.Navigation("MusicFiles");
                });

            modelBuilder.Entity("MusicServer.API.Models.Genre", b =>
                {
                    b.Navigation("MusicFiles");
                });

            modelBuilder.Entity("MusicServer.API.Models.MusicFile", b =>
                {
                    b.Navigation("ExtraFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
